### ISSUE TITLE
Few-NERD数据集

### ISSUE THREAD

**Issue by XxxAtlantis** [liyongqi2002/TadNER#1]
能否提供跑fewnerd数据集的sh脚本？ 对跑fewnerd数据集有点疑惑。

**Comment by liyongqi2002** [comment]
感谢关注我们的工作，我已经更新了repo，您可以重新查看。

Thanks for your attention, I've updated this repo so you can revisit it.

**Comment by Serega6678** [comment]
For your Few-NERD experiments, did you create span and type models on the conll dataset?
Am I right that just by
1.  Downloading FEW-NERD dataset
2. Downloading Conll dataset
3. Running run_fewnerd.sh
I will be able to reproduce the paper results and there's no need to tune any parameters?
Thank you very much
