### ISSUE TITLE
关于train训练集的问题

### ISSUE THREAD

**Issue by ljz00** [liyongqi2002/TadNER#2]
请问原本的FEWNERD数据集中的train_5_1.jsonl如何转化成模型训练时需要的train.txt，我想要使用您的代码探索一些小样本NER的问题，所以想要尝试更多不同数据集的测试。

**Comment by liyongqi2002** [comment]
https://github.com/thunlp/Few-NERD/blob/main/data/download.sh

Few-NERD官方提供了相关链接
具体地，inter https://cloud.tsinghua.edu.cn/f/3d84d34dc5d845a2bed2/?dl=1  intra  https://cloud.tsinghua.edu.cn/f/a176a4870f0a4f8ba0db/?dl=1

**Comment by ljz00** [comment]
十分感谢您的回答，还有一个问题就是我按照您上传的代码未做修改的复现，但我的结果仍比您论文上的效果要差很多
![de239095e9cc79bd369daa0d523a243](https://github.com/liyongqi2002/TadNER/assets/71304339/c28fbcda-c36e-4bca-8a7e-0e8bdc710ed6)

**Comment by liyongqi2002** [comment]
我这里重新跑了一下run_fewnerd.sh，结果大概是正常的，这个代码应该是没问题的，可能是环境之类的问题（和requirements.txt里面的对齐）
![image](https://github.com/liyongqi2002/TadNER/assets/57225048/24d57e7b-9398-4c0c-8a2c-d3a9e8f228f8)

**Comment by ljz00** [comment]
好的，叨扰了，十分感谢您的回答

**Comment by Serega6678** [comment]
Hello, thank you very much for your work
How did you calculate the confidence interval (from the paper) based on the output of the evaluation script?

**Comment by liyongqi2002** [comment]
> Hello, thank you very much for your work How did you calculate the confidence interval (from the paper) based on the output of the evaluation script?

https://github.com/liyongqi2002/TadNER/issues/3#issuecomment-1851203922
