### ISSUE TITLE
Confidence interval calculation

### ISSUE THREAD

**Issue by Serega6678** [liyongqi2002/TadNER#3]
Hello, thank you very much for your work
How did you calculate the confidence interval (from the paper) based on the output of the evaluation script?

**Comment by liyongqi2002** [comment]
Thank you for your interest in our work! 
But I'm sorry I didn't fully understand your question, did you mean the "cal_span_threshold" function?
https://github.com/liyongqi2002/TadNER/blob/2c5bf93b797f338393c81b3439d127d14fb6c1da/evaluate.py#L1041

**Comment by Serega6678** [comment]
Thanks for the response
I mean that in the paper you report results like 39.3±3.8. How did you get that ±3.8? Did you do several runs? How did you get this 3.8 value? Is it standard deviation?

**Comment by liyongqi2002** [comment]
> Thanks for the response I mean that in the paper you report results like 39.3±3.8. How did you get that ±3.8? Did you do several runs? How did you get this 3.8 value? Is it standard deviation?

Yes, it is standard deviation. Following previous works (Container, decomposedmetaNER), for the Few-Nerd settings, it is computed by 5 runs using different seeds. For the domain transfer settings, it is computed by 10 diifferent support    sets, using the same seed 42.

**Comment by Serega6678** [comment]
Thank you very much

**Comment by sehbe** [comment]
你好，感谢你清晰明了的代码。我想问一下对于domain transfer settings的f1值的评估，你说的10次不同的抽样该怎么操作呢，有可以操作的参数吗？还是该怎么来实现？

**Comment by sehbe** [comment]
@liyongqi2002 你好，感谢你清晰明了的代码。我想问一下对于domain transfer settings的f1值的评估，你说的10次不同的抽样该怎么操作呢，有可以操作的参数吗？还是该怎么来实现？

**Comment by liyongqi2002** [comment]
> @liyongqi2002 你好，感谢你清晰明了的代码。我想问一下对于domain transfer settings的f1值的评估，你说的10次不同的抽样该怎么操作呢，有可以操作的参数吗？还是该怎么来实现？

这个采样的具体操作算法是structshot ["Simple and Effective Few-Shot Named Entity Recognition with Structured Nearest Neighbor Learning"](https://arxiv.org/abs/2010.02405), Yi Yang and Arzoo Katiyar, in EMNLP 2020. 提出来的，他们论文里有详细说明。
![image](https://github.com/liyongqi2002/TadNER/assets/57225048/affd1386-c388-4320-91aa-712cae920b74)


我们这里的10次采样是用Container [CONTaiNER: Few-Shot Named Entity Recognition via Contrastive Learning](https://arxiv.org/pdf/2109.07589.pdf)所提供的（为了公平对比）

**Comment by sehbe** [comment]
感谢你这么认真的解答，我还有个疑问，我能跑出来标准差，我跑出来的结果如下:
![捕获](https://github.com/liyongqi2002/TadNER/assets/44962530/2b3124a2-684d-472f-be2f-04d9d661918a)
那我的结果换算到你论文的结果，是不是就是69.3±9.16，再次感谢你的解答

**Comment by sehbe** [comment]
@liyongqi2002 感谢你这么认真的解答，我还有个疑问，我能跑出来标准差，我跑出来的结果如下:
![捕获](https://github.com/liyongqi2002/TadNER/assets/44962530/0be91cd0-9850-498c-8440-6f998f60a663)

那我的结果换算到你论文的结果，是不是就是69.3±9.16，再次感谢你的解答

**Comment by liyongqi2002** [comment]
> @liyongqi2002 感谢你这么认真的解答，我还有个疑问，我能跑出来标准差，我跑出来的结果如下: ![捕获](https://private-user-images.githubusercontent.com/44962530/292393079-0be91cd0-9850-498c-8440-6f998f60a663.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjgwOTIsIm5iZiI6MTcwMzIyNzc5MiwicGF0aCI6Ii80NDk2MjUzMC8yOTIzOTMwNzktMGJlOTFjZDAtOTg1MC00OThjLTg0NDAtNmY5OThmNjBhNjYzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA2NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZDEwNWVmZDI1NWM4ZmE2MWRjYzFiMWFiM2FiM2NlNmE0MzE4OGFhZjFlMjUzMDdjNGM5Y2ZkYTMwZjY4N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l3zijjLAnzjfbzGPl_YMdP6Y1rF8g_Cr7gPs39GPdxI)
> 
> 那我的结果换算到你论文的结果，是不是就是69.3±9.16，再次感谢你的解答

对；和论文结果略有差异可能是种子或者机器差异，我没有仔细调整，不过不影响实验结果的显著性。

不客气，如果觉得本工作对您有所帮助，欢迎star或后续引用本文！

**Comment by sehbe** [comment]
@liyongqi2002 我还有一个问题，麻烦你了，就是I2B2的test.txt数据集要怎么才能获得？具体要怎么操作呢？

**Comment by liyongqi2002** [comment]
> @liyongqi2002 我还有一个问题，麻烦你了，就是I2B2的test.txt数据集要怎么才能获得？具体要怎么操作呢？

I2B2数据集也可以在他们的官网上下载（https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/）

处理方式可以参考：
https://github.com/EmilyAlsentzer/clinicalBERT/blob/a9d91698929b7189311bba364ccdd0360e847276/downstream_tasks/i2b2_preprocessing/i2b2_2012/Reformat.ipynb

**Comment by mihua5329** [comment]
> > Thanks for the response I mean that in the paper you report results like 39.3±3.8. How did you get that ±3.8? Did you do several runs? How did you get this 3.8 value? Is it standard deviation?
> 
> Yes, it is standard deviation. Following previous works (Container, decomposedmetaNER), for the Few-Nerd settings, it is computed by 5 runs using different seeds. For the domain transfer settings, it is computed by 10 diifferent support sets, using the same seed 42.

你好，想问下对于域迁移设置下，评估使用的十个支持集是data_raw文件夹下提供的这十个吗
