### ISSUE TITLE
关于Zero-shot部分

### ISSUE THREAD

**Issue by Ustinian12** [liyongqi2002/TadNER#4]
您好，有点好奇Zero-shot部分的实验的设置是怎样的？实体抽取器有在OntoNotes上进行微调吗？类型判别器有在OntoNotes上进行微调吗？

**Comment by liyongqi2002** [comment]
感谢关注，span detector和type classifier都有在OntoNotes（源域）上预先微调，然后直接在目标域上预测；由于目标域上没有给标注数据（源域和目标域的类别集合不同），所以称之为zero-shot设置。
对于bert这种规模的LM，不给任何源域标注数据是几乎无法完成NER任务的，所以要先给源域。

**Comment by Ustinian12** [comment]
感谢回复，类型判别器在OntoNotes（源域）上预先微调的具体设置是什么呢？N-way-k-shot吗？如果是，N和k具体是几呢？

**Comment by liyongqi2002** [comment]
> 感谢回复，类型判别器在OntoNotes（源域）上预先微调的具体设置是什么呢？N-way-k-shot吗？如果是，N和k具体是几呢？

预先微调就直接拿train set进行，因为本文没有采用元学习的方式，所以并没有先采样N-way-k-shot再元训练。

**Comment by Ustinian12** [comment]
原来如此，那么“源域和目标域的类别集合不同”但是是有重合的部分，关于这部分有做清洗吗？

**Comment by liyongqi2002** [comment]
> 原来如此，那么“源域和目标域的类别集合不同”但是是有重合的部分，关于这部分有做清洗吗？

这里我们做的设置是不单独清洗重合部分，因为很难制定重合的标准（例如不同数据集对于相似的实体类别的表述不同，比如person和PER；），而且zero-shot实际上不是我们这个工作关心的重点，只是提供了一种可能性，所以没有做过多的详细阐述。

你可以参考我们在zero-shot实验部分对比的SpanNER [Learning from Language Description: Low-shot Named Entity Recognition via Decomposed Framework](https://aclanthology.org/2021.findings-emnlp.139.pdf)，在他们的文章中考虑了“是否清洗重合标签”的不同设置。

**Comment by Ustinian12** [comment]
感谢您的回复！！！

**Comment by liyongqi2002** [comment]
> 感谢您的回复！！！

不客气，如果觉得本工作对您有所帮助，欢迎star或后续引用本文！
