### ISSUE TITLE
data_raw下的I2B2缺少test.txt文件

### ISSUE THREAD

**Issue by Kumasy-id** [liyongqi2002/TadNER#6]
你好，我发现代码在data_raw给出的I2B2上运行时会因为缺少test.txt而无法继续，我也没有在官方的I2B2和n2c2数据集下找到类似的文件，请问这个文件如何获得？或者说对于I2B2不需要这个文件？

**Comment by liyongqi2002** [comment]
I2B2数据集也可以在他们的官网上下载（[https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/）](https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/%EF%BC%89)

处理方式可以参考：
https://github.com/EmilyAlsentzer/clinicalBERT/blob/a9d91698929b7189311bba364ccdd0360e847276/downstream_tasks/i2b2_preprocessing/i2b2_2012/Reformat.ipynb

如果依然有困难，可以私发邮件交流
